spring:
  application:
    name: web-ban-hang

  datasource:
    url: jdbc:mysql://localhost:3306/WebBanHang?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 123456Aa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    serialization:
      write-dates-as-timestamps: false

  sql:
    init:
      mode: never

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: d9e960e5c84553
    password: 45eea32a46c461
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 181934678225-8v0p6a1jmir30b9394fhnrohbiu71eek.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

          facebook:
            client-id: 1264921768477871
            client-secret: 55228be8aa48f10335f9006f35f17069
            scope:
              - email
              - public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"

        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id

  mvc:
    async:
      request-timeout: 90000
server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      cookie:
        same-site: lax    # ← thêm
        secure: false

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off

cloudinary:
  cloud-name: dkzmro70z
  api-key: 823543818962586
  api-secret: toCQQtRfGrqsZeTmg-kShKb6-44

vnpay:
  tmn-code: RDA0RUVD
  hash-secret: ZR1LO2OJT5DISAG3CPQUKLPTNQ9EBR50
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:9090/api/payments/vnpay-callback
  version: "2.1.0"
  command: pay
  currency-code: VND
  locale: vn

ai:
  pinecone:
    api-key: pcsk_5PYocA_TdJ7LYuQHHvAR1fhDafh79VGz4LbAkhZp14x5DDTct19vsL2GTkkTSLt6GGTiWJ         # ← copy từ .env PINECONE_API_KEY
    index-host: https://my-index-p9os2w5.svc.aped-4627-b74a.pinecone.io
  openrouter:
    api-key: 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     # ← copy từ .env OPENROUTER_API_KEY
    model: openai/gpt-oss-120b
  voyage:
    api-key: pa-SxxHjUXYLfh-jp6g-pMcGP2T59Yrt-s9vytNQVfqln3              # ← copy từ .env HF_API_KEY
app:
  frontend-url: http://localhost:5173
  oauth2:
    redirect-uri: http://localhost:5173/oauth2/callback